package reportgen

import (
	"fmt"
	"strings"
	"time"

	"github.com/codeledger/codeledger/internal/model"
	"github.com/codeledger/codeledger/internal/service"
	"github.com/codeledger/codeledger/internal/store"
)

// GenerateReport generates a Markdown progress report.
func GenerateReport(s *store.Store) (string, error) {
	p, err := s.ReadProject()
	if err != nil {
		return "", err
	}

	status, err := service.GetStatus(s)
	if err != nil {
		return "", err
	}

	recentDone, err := service.GetRecentDoneTasks(s, 20)
	if err != nil {
		return "", err
	}

	files, err := service.GetModifiedFiles(s)
	if err != nil {
		return "", err
	}

	testResults, err := service.GetTestResults(s)
	if err != nil {
		return "", err
	}

	allTasks, err := service.ListTasks(s, "")
	if err != nil {
		return "", err
	}

	date := time.Now().Format("2006-01-02")

	var b strings.Builder

	b.WriteString(fmt.Sprintf("# Progress Report - %s\n\n", date))
	b.WriteString(fmt.Sprintf("**Project:** %s\n\n", p.Name))
	if p.Goal != "" {
		b.WriteString(fmt.Sprintf("**Goal:** %s\n\n", p.Goal))
	}

	// Overview
	b.WriteString("## Overview\n\n")
	b.WriteString(fmt.Sprintf("| Status | Count |\n"))
	b.WriteString(fmt.Sprintf("|--------|-------|\n"))
	b.WriteString(fmt.Sprintf("| Total | %d |\n", status.Total))
	b.WriteString(fmt.Sprintf("| Pending | %d |\n", status.Pending))
	b.WriteString(fmt.Sprintf("| In Progress | %d |\n", status.InProgress))
	b.WriteString(fmt.Sprintf("| Done | %d |\n", status.Done))
	b.WriteString(fmt.Sprintf("| Blocked | %d |\n", status.Blocked))
	b.WriteString("\n")

	// Completed Tasks
	if len(recentDone) > 0 {
		b.WriteString("## Completed Tasks\n\n")
		for _, t := range recentDone {
			b.WriteString(fmt.Sprintf("- **%s:** %s", t.ID, t.Title))
			if len(t.Files) > 0 {
				b.WriteString(fmt.Sprintf(" (%s)", strings.Join(t.Files, ", ")))
			}
			b.WriteString("\n")
			if strings.Join(t.Evidence, ", ") != "" {
				b.WriteString(fmt.Sprintf("  - Evidence: `%s`\n", strings.Join(t.Evidence, ", ")))
			}
		}
		b.WriteString("\n")
	}

	// In Progress Tasks
	var inProgressTasks []model.Task
	for _, t := range allTasks {
		if t.Status == model.StatusInProgress {
			inProgressTasks = append(inProgressTasks, t)
		}
	}
	if len(inProgressTasks) > 0 {
		b.WriteString("## In Progress\n\n")
		for _, t := range inProgressTasks {
			b.WriteString(fmt.Sprintf("- **%s:** %s\n", t.ID, t.Title))
		}
		b.WriteString("\n")
	}

	// Blocked Tasks
	if len(status.BlockedTasks) > 0 {
		b.WriteString("## Blocked\n\n")
		for _, t := range status.BlockedTasks {
			b.WriteString(fmt.Sprintf("- **%s:** %s\n", t.ID, t.Title))
			if t.BlockedReason != "" {
				b.WriteString(fmt.Sprintf("  - **Reason:** %s\n", t.BlockedReason))
			}
		}
		b.WriteString("\n")
	}

	// Modified Files
	if len(files) > 0 {
		b.WriteString("## Modified Files\n\n")
		b.WriteString("```\n")
		for _, f := range files {
			b.WriteString(f + "\n")
		}
		b.WriteString("```\n\n")
	}

	// Test Results
	if len(testResults) > 0 {
		b.WriteString("## Test Results\n\n")
		b.WriteString("| Task | Command | Result |\n")
		b.WriteString("|------|---------|--------|\n")
		for _, t := range testResults {
			result := t.Test.Result
			if result == "" {
				result = "unknown"
			}
			b.WriteString(fmt.Sprintf("| %s | `%s` | %s |\n", t.ID, t.Test.Command, result))
		}
		b.WriteString("\n")
	}

	// Risks
	b.WriteString("## Risks\n\n")
	if len(status.BlockedTasks) > 0 {
		b.WriteString(fmt.Sprintf("- %d blocked task(s) need resolution.\n", len(status.BlockedTasks)))
	}
	if status.Pending+status.InProgress > 0 {
		b.WriteString(fmt.Sprintf("- %d task(s) remaining.\n", status.Pending+status.InProgress))
	}
	if status.Pending+status.InProgress == 0 && status.Blocked == 0 {
		b.WriteString("- No remaining tasks.\n")
	}
	b.WriteString("\n")

	// Next Steps
	b.WriteString("## Next Steps\n\n")
	if status.NextTask != nil {
		b.WriteString(fmt.Sprintf("1. Start **%s:** %s\n", status.NextTask.ID, status.NextTask.Title))
	}
	if len(status.BlockedTasks) > 0 {
		b.WriteString(fmt.Sprintf("2. Resolve blocked task(s): "))
		var blockedIDs []string
		for _, t := range status.BlockedTasks {
			blockedIDs = append(blockedIDs, t.ID)
		}
		b.WriteString(strings.Join(blockedIDs, ", ") + "\n")
	}
	if status.Pending == 0 && status.InProgress == 0 && status.Blocked == 0 {
		b.WriteString("All tasks are complete.\n")
	}
	b.WriteString("\n")

	b.WriteString("---\n")
	b.WriteString(fmt.Sprintf("_Generated by CodeLedger on %s_\n", date))

	return b.String(), nil
}
